version: 0.2

phases:
  install:
    commands:
      - echo install phase started
  pre_build:
    commands:
      - echo pre_build phase started
      - echo Test started on `date`
  build:
    commands:
      - echo build phase started
      - echo Build started on `date`
  post_build:
    commands:
      - echo post build phase started
      - echo Post Build started on `date`
  artifacts:
  files:
    MongoDbCurdDemo*.jar

      
